# Orb 'circleci/maven@0.0.12' resolved to 'circleci/maven@0.0.12'
version: 2
jobs:
  maven/test:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - run:
          name: Generate Cache Checksum
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
      - restore_cache:
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - run:
          name: Install Dependencies
          command: mvn dependency:go-offline --settings 'pom.xml'

      - run: mvn install -DskipTests

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
            -

      # run tests!
      - run: mvn integration-test

# Original config.yml file:
# version: 2.1
# 
# orbs:
#   maven: circleci/maven@0.0.12
# 
# workflows:
#   maven_test:
#     jobs:
#       - maven/test # checkout, build, test, and upload test results